Repository pyro-yolog/yolog-front, pull requests merged in 2024-07, with the labels that each got.

#36 [#35] feat: 온보딩 개편
  app/components/background-color.tsx
  app/components/bottom-sheet.tsx
  app/components/diary-book/index.ts
  app/components/diary/create/cover-form.tsx
  app/components/diary/create/cover-palette.tsx
  app/components/diary/create/index.ts
  app/components/diary/create/setting-period.tsx
  app/components/diary/create/setting-title.tsx
  app/components/index.ts
  app/components/onboarding/bottom-sheet.tsx
  app/components/onboarding/bottom.tsx
  app/components/onboarding/index.ts
  app/components/onboarding/pagination.tsx
  app/components/ui/onboarding-image-swiper.tsx
  app/components/ui/onboarding-text-swiper.tsx
  app/components/ui/signin-bottom.tsx
  app/components/ui/social-bottom-sheet.tsx
  app/components/ui/social-button.tsx
  app/diary/create/cover/page.tsx
  app/diary/create/setting/page.tsx
  app/globals.css
  app/layout.tsx
  app/lib/constants/onboarding-image-slides.ts
  app/lib/constants/onboarding-text-slides.ts
  app/onboarding/page.tsx
  app/page.tsx
  app/sign/page.tsx
  public/images/onboarding.avif
  public/images/onboarding1.png
  public/images/onboarding2.png
  public/images/onboarding3.png
  public/images/sign1.png
  public/images/sign2.png
  stories/bottom-sheet.stories.tsx
  tailwind.config.ts
Labels: 🌈 기능 구현

#44 [#42] feat: Docker 설정
  .dockerignore
  Dockerfile
  next.config.mjs
Labels: 🌈 기능 구현

#46 feat: CI/CD 구축
  .github/workflows/gradle.yml
Labels: 🌈 기능 구현

#48 [#47] API 호출 proxy 수정
  apis/config/instance.ts
  next.config.mjs
Labels: 🔨 리팩토링

#49 [#47] refactor: API prefix 추가
  app/components/ui/social-button.tsx
Labels: 🔨 리팩토링

#50 [#43] refactor: 일기장 페이지 재구현
  apis/diaries.ts
  apis/trips.ts
  app/components/diary/setting/index.ts
  app/components/icon/icon-calendar.tsx
  app/components/icon/icon-chevron-down.tsx
  app/components/icon/icon-navigate-left.tsx
  app/components/icon/icon-setting.tsx
  app/components/icon/icon-smile.tsx
  app/components/icon/icon-sun.tsx
  app/components/icon/index.ts
  app/components/index.ts
  app/components/toast-container.tsx
  app/components/trip/detail/date-picker.tsx
  app/components/trip/detail/diary-item.tsx
  app/components/trip/detail/diary-list-empty.tsx
  app/components/trip/detail/diary-list.tsx
  app/components/trip/detail/diary-view.tsx
  app/components/trip/detail/index.ts
  app/components/trip/detail/visual-loading.tsx
  app/components/trip/detail/visual.tsx
  app/components/trip/main/item.tsx
  app/components/trip/main/view.tsx
  app/components/trip/setting/calendar-modal.tsx
  app/components/trip/setting/cover-modal-option.tsx
  app/components/trip/setting/cover-modal-palette.tsx
  app/components/trip/setting/cover-modal.tsx
  app/components/trip/setting/cover.tsx
  app/components/trip/setting/date-confirm-modal.tsx
  app/components/trip/setting/delete-modal.tsx
  app/components/trip/setting/delete.tsx
  app/components/trip/setting/form.tsx
  app/components/trip/setting/index.ts
  app/trip/[id]/page.tsx
  app/trip/[id]/setting/page.tsx
  lib/Providers.tsx
  lib/utils/date.ts
  models/diary.model.ts
  tailwind.config.ts
Labels: 🔨 리팩토링

#52 [#51] fix: 레이아웃 수정
  app/components/bottom-sheet.tsx
  app/components/menu.tsx
  app/components/onboarding/bottom-sheet.tsx
  app/components/toast-container.tsx
  app/components/trip/create/cover-form.tsx
  app/components/ui/dialog-account-withdrawal.tsx
  app/components/ui/dialog-logout.tsx
  app/layout.tsx
  app/sign/page.tsx
  hooks/useToast.ts
  tailwind.config.ts
Labels: 🐞 버그픽스

#56 feat: 일기장 생성 - 사진 선택 기능 재구현
  app/components/background-color.tsx
  app/components/icon/icon-plus.tsx
  app/components/trip/create/cover-form.tsx
  app/components/trip/create/cover-image.tsx
  app/components/trip/create/cover-palette.tsx
  app/components/trip/create/spine-palette.tsx
  app/components/trip/detail/date-picker.tsx
  app/components/trip/detail/visual.tsx
  app/components/trip/main/item.tsx
  app/components/trip/setting/cover-modal-palette.tsx
  app/onboarding/page.tsx
  app/signup/profile/page.tsx
  app/signup/terms/page.tsx
  lib/constants/colors.ts
  lib/store/ui.ts
  models/trip.model.ts
Labels: 🌈 기능 구현

#54 [#53] feat: 일기 작성 구현
  apis/diaries.ts
  apis/images.ts
  app/components/background-color.tsx
  app/components/icon/icon-align-left.tsx
  app/components/icon/icon-camera.tsx
  app/components/icon/icon-plus-circle.tsx
  app/components/icon/icon-timeline.tsx
  app/components/icon/index.ts
  app/components/index.ts
  app/components/trip/create/cover-image.tsx
  app/components/trip/detail/diary-list-empty.tsx
  app/components/trip/detail/diary-list.tsx
  app/components/trip/diary/write/additional-box.tsx
  app/components/trip/diary/write/cancel-bottom-sheet.tsx
  app/components/trip/diary/write/emotion-box.tsx
  app/components/trip/diary/write/form-content.tsx
  app/components/trip/diary/write/form-timeline-items.tsx
  app/components/trip/diary/write/form-timeline.tsx
  app/components/trip/diary/write/form.tsx
  app/components/trip/diary/write/header.tsx
  app/components/trip/diary/write/index.ts
  app/components/trip/diary/write/weather-box.tsx
  app/globals.css
  app/trip/[id]/diary/write/page.tsx
  app/trip/[id]/page.tsx
  lib/constants/diary-additional.ts
  lib/store/diary.ts
  lib/store/ui.ts
  lib/utils/date.ts
  lib/utils/number.ts
  models/diary.model.ts
  models/image.model.ts
  public/images/emotion-angry.png
  public/images/emotion-happy.png
  public/images/emotion-normal.png
  public/images/emotion-tired.png
  public/images/emotion-upset.png
  public/images/weather-cloudy.png
  public/images/weather-rain.png
  public/images/weather-snow.png
  public/images/weather-sunny.png
  public/images/weather-winds.png
Labels: 🌈 기능 구현
